#!/bin/bash

alias gemset='rvm gemset'

#Alias para o ack-grep
alias pgrep="ag-grep -i --ignore-dir=features/cassettes/ --ignore-dir=spec/cassettes/ --ignore-dir=spec/reports/ --ignore-dir=coverage/ --ignore-dir=spec/fixtures/ --ignore-dir=log/"

# Alias para subir Programas
# VPN
alias vpn="cd $OTHER_PROGRAMS_HOME/jvpn && sudo ./jvpn.pl"

# Projetos
