#!/bin/bash

alias gemset='rvm gemset'

#Alias para o ack-grep
alias pgrep="ack-grep -i --ignore-dir=features/cassettes/ --ignore-dir=spec/cassettes/ --ignore-dir=spec/reports/ --ignore-dir=coverage/ --ignore-dir=spec/fixtures/ --ignore-dir=log/"

# Alias para subir Programas
# VPN
alias vpn="cd $OTHER_PROGRAMS_HOME/jvpn && sudo ./jvpn.pl"

# GenyMotion
alias genymotion="cd $OTHER_PROGRAMS_HOME/genymotion && ./genymotion"

# Projetos

alias veja="cd $VEJA_HOME"
alias alx="cd $ALX_HOME"
