#!/bin/bash

alias gemset='rvm gemset'

#Alias para o ack-grep
alias pgrep="ag -i --ignore-dir=features/cassettes/ --ignore-dir=spec/cassettes/ --ignore-dir=spec/reports/ --ignore-dir=coverage/ --ignore-dir=spec/fixtures/ --ignore-dir=log/ --ignore-dir=tmp/"

alias drspec="rspec --format=documentation"
