#!/bin/bash

echo "Copiando arquivos de configuração"

cp "../dotfiles/bash_aliases" "~/.bash_aliases"
cp "../dotfiles/bash_environment" "~/.bash_environment"
cp "../dotfiles/gitconfig" "~/.gitconfig"
cp "../dotfiles/gitignore_global" "~/.gitignore_global"
cp "../dotfiles/rspec" "~/.rspec"
cp "../dotfiles/tmux.conf" "~/.tmux.conf"

source "~/.bashrc"
